# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: splash.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'splash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csplash.proto\x12\x06splash\"w\n\nUpdateItem\x12\x0e\n\x06\x42\x61nner\x18\x05 \x01(\t\x12\x0f\n\x07\x44\x65tails\x18\t \x01(\t\x12\r\n\x05Start\x18\n \x01(\x03\x12\x0b\n\x03\x45nd\x18\x0b \x01(\x03\x12\r\n\x05Title\x18\x03 \x01(\t\x12\x0c\n\x04Link\x18\x08 \x01(\t\x12\x0f\n\x07LinkAlt\x18\x14 \x01(\t\"2\n\rUpdateSection\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.splash.UpdateItem\"f\n\tEventItem\x12\x0e\n\x06\x42\x61nner\x18\x0e \x01(\t\x12\r\n\x05Start\x18\x06 \x01(\x03\x12\x0b\n\x03\x45nd\x18\x07 \x01(\x03\x12\r\n\x05Title\x18\x04 \x01(\t\x12\x10\n\x08TitleAlt\x18\x03 \x01(\t\x12\x0c\n\x04Link\x18\x0c \x01(\t\"0\n\x0c\x45ventSection\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.splash.EventItem\"^\n\x0eSplashResponse\x12&\n\x07updates\x18\x01 \x01(\x0b\x32\x15.splash.UpdateSection\x12$\n\x06\x65vents\x18\x02 \x01(\x0b\x32\x14.splash.EventSectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'splash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEITEM']._serialized_start=24
  _globals['_UPDATEITEM']._serialized_end=143
  _globals['_UPDATESECTION']._serialized_start=145
  _globals['_UPDATESECTION']._serialized_end=195
  _globals['_EVENTITEM']._serialized_start=197
  _globals['_EVENTITEM']._serialized_end=299
  _globals['_EVENTSECTION']._serialized_start=301
  _globals['_EVENTSECTION']._serialized_end=349
  _globals['_SPLASHRESPONSE']._serialized_start=351
  _globals['_SPLASHRESPONSE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
